#!/usr/bin/env bash
#
# test_locked_lockfile.sh — positive control proving `cargo metadata
# --locked --format-version 1` actually distinguishes a stale Cargo.lock
# from a current one (MV.ticket.locked-lockfile-check task 1).
#
# The harness row this test backs (`locked-lockfile`) is worthless unless
# the command underneath it has been observed going red on a real stale
# lock. This script builds a throwaway crate under mktemp -d, exercises
# the command against a deliberately stale lock (must fail, with the
# specific "cannot update the lock file" message — not just any nonzero
# exit), then regenerates that SAME fixture's lock and asserts the same
# command now passes. Only the second half rules out a fixture that is
# merely broken for an unrelated reason.
#
# Everything happens in a temp dir; nothing in this repo (including this
# repo's own Cargo.lock) is ever touched. Uses --offline throughout, so
# no network access is required.
#
#   bash scripts/test_locked_lockfile.sh
#
# Exit status 0 = both cases passed; non-zero = at least one failure.
#
set -uo pipefail

fail=0
pass_count=0
fail_count=0
check() { # check <description> <result: 0=pass>
    if [ "$2" -eq 0 ]; then
        printf 'ok   %s\n' "$1"
        pass_count=$((pass_count + 1))
    else
        printf 'FAIL %s\n' "$1"
        fail=1
        fail_count=$((fail_count + 1))
    fi
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

CRATE="$WORK/fixture-crate"
mkdir -p "$CRATE/src"

cat > "$CRATE/Cargo.toml" <<'TOML'
[package]
name = "fixture-crate"
version = "0.1.0"
edition = "2021"

[dependencies]
itoa = "1"
TOML

cat > "$CRATE/src/lib.rs" <<'RS'
// fixture crate for scripts/test_locked_lockfile.sh — never built, only
// used as a `cargo metadata` target.
RS

# ---------------------------------------------------------------------------
# Case 1: a hand-written Cargo.lock that omits the declared dependency is
# stale — `cargo metadata --locked` must refuse to proceed rather than
# silently regenerate it, and must say why.
# ---------------------------------------------------------------------------
cat > "$CRATE/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "fixture-crate"
version = "0.1.0"
LOCK

STALE_OUT="$(cd "$CRATE" && cargo metadata --offline --locked --format-version 1 2>&1 >/dev/null)"
STALE_RC=$?

check "stale lock: cargo metadata --locked exits non-zero" \
    "$( [ "$STALE_RC" -ne 0 ] && echo 0 || echo 1 )"
check "stale lock: stderr names the specific failure ('cannot update the lock file')" \
    "$(printf '%s' "$STALE_OUT" | grep -q 'cannot update the lock file' && echo 0 || echo 1)"

# ---------------------------------------------------------------------------
# Case 2: regenerating the SAME fixture's lock makes the identical command
# pass. Load-bearing half — without it, case 1 could pass for an unrelated
# reason (e.g. a broken manifest) rather than because the lock was stale.
# ---------------------------------------------------------------------------
(cd "$CRATE" && cargo generate-lockfile --offline >/dev/null 2>&1)
GEN_RC=$?
check "regenerating the lock succeeds offline" \
    "$( [ "$GEN_RC" -eq 0 ] && echo 0 || echo 1 )"

(cd "$CRATE" && cargo metadata --offline --locked --format-version 1 >/dev/null 2>&1)
FRESH_RC=$?
check "SAME fixture, lock regenerated: cargo metadata --locked now exits 0" \
    "$( [ "$FRESH_RC" -eq 0 ] && echo 0 || echo 1 )"

# ---------------------------------------------------------------------------
# Isolation guard: this script must never touch the real repo.
# ---------------------------------------------------------------------------
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SELF_BASENAME="$(basename "$0")"
REPO_STATUS="$(cd "$REPO_ROOT" && git status --short -- . ":(exclude)scripts/$SELF_BASENAME")"
check "this repo's own working tree is untouched (git status --short empty, excluding this script itself)" \
    "$( [ -z "$REPO_STATUS" ] && echo 0 || echo 1 )"

check "test_locked_lockfile.sh passes bash -n" \
    "$(bash -n "$0" 2>/dev/null && echo 0 || echo 1)"

echo
echo "== $pass_count passed, $fail_count failed =="
exit "$fail"
